[metadata]
name = annotix-ml
version = 0.0.1
description = Predict unknown molecular structures from MS/MS spectra using machine learning.
long_description = file: README.md

[options]
packages = find:
install_requires =
  spec2vec
  pandas
  matchms
  matplotlib
  tqdm
  loguru
  numpy
  scipy
  psycopg2-binary
  torch
