run:
  project: annotix_msg
  name: baseline_no_ms2

dataset:
  data_path: data/msg/labels_.csv
  spec_folder: data/msg/spec_files
  subform_folder: data/msg/subformulae/default_subformulae
  datadir: data/BanyulsInference
  labels_file: data/BanyulsInference/labels.tsv
  morgan_nbits: 2048

model:
  y_update: False
  no_y: True
  diffusion_steps: 500
  noise_strategy: distribution
  num_ev: 2
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features

train:
  num_train_steps: 100000
  save_path: logs/msg/baseline_no_ms2
  save_steps: 4000
  distributed: "pipeline"
  num_microbatches: 4
