run:
  project: annotix_ml
  name: digress_base

dataset:
  data_path: data/qm9.csv
  smile_column: smiles
  split_column: split

model:
  d: 256
  de: 64
  dy: 64
  n_heads: 8
  n_layers: 6
  diffusion_steps: 500
  noise_strategy: distribution
  last_layer: mlp
  num_ev: 2
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features

train:
  batch_size: 512
  num_train_steps: 10000
  loss_ratio: 1
  starting_learning_rate: 0.0002
  final_learning_rate: 0.000001
  learning_rate_schedule: cosine
  save_path: logs/qm9_experiment
  save_steps: 1000
  num_workers: 4
  seed: 24

valid:
  batch_size: 2048
  num_samples: 1024
  num_eval_steps: 500
