dataset:
  data_path: data/MassSpecGym.csv
  smile_column: smiles
  split_column: "fold"

model:
  d: 256
  de: 64
  dy: 64
  n_heads: 8
  n_layers: 5
  diffusion_steps: 500
  num_ev: 10
  extra_features:
    - laplacian_embedding
    - node_cycle

train:
  batch_size: 64
  loss_ratio: 1

valid:
  batch_size: 128
  num_eval_steps: 1000

test:
  batch_size: 128
