run:
  project: annotix_ml_moses
  name: digress_medium_wide

dataset:
  data_path: data/moses.csv
  smile_column: SMILES
  split_column: SPLIT

model:
  d: 384
  de: 96
  dy: 96
  n_heads: 12
  n_layers: 5
  diffusion_steps: 500
  noise_strategy: distribution
  last_layer: mlp
  num_ev: 5
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features

train:
  batch_size: 512
  num_train_steps: 100000
  save_path: logs/moses_medium_wide
