run:
  project: annotix_msg
  name: baseline_ms2

dataset:
  data_path: data/msg/labels_.csv
  spec_folder: data/msg/spec_files
  subform_folder: data/msg/subformulae/default_subformulae
  datadir: data/BanyulsInference
  labels_file: data/BanyulsInference/labels.tsv
  morgan_nbits: 2048
  cache_path: data/cache/msg_50nodes
  val_tag: test
  max_nodes: 40

model:
  y_update: False
  no_y: True
  diffusion_steps: 500
  noise_strategy: distribution
  num_ev: 2
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features
    - spectra_fingerprint

spectra_encoder:
  form_embedder: pos-cos
  output_size: 4096
  hidden_size: 512
  spectra_dropout: 0
  top_layers: 1
  magma_modulo: 2048
  peak_attn_layers: 2
  set_pooling: intensity
  pairwise_featurization: True
  num_heads: 8
  embed_instrument: False
  inten_transform: float
  no_diffs: False
  refine_layers: 4
  checkpoint_path: checkpoints/encoder_msg.pt

train:
  num_train_steps: 100000
  save_path: logs/msg/baseline_no_ms2
  save_steps: 4000
  distributed: "pipeline"
  num_microbatches: 4
