run:
  project: annotix_ml
  name: digress_medium_long

model:
  d: 256
  de: 64
  dy: 64
  n_heads: 8
  n_layers: 12
  diffusion_steps: 500
  noise_strategy: distribution
  num_ev: 2
  no_y: True
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features

train:
  batch_size: 512
  num_train_steps: 40000
  save_path: logs/qm9_medium_long
  distributed: "pipeline"
  num_microbatches: 4
