run:
  project: annotix_ml
  name: digress_base

dataset:
  data_path: data/qm9.csv
  smile_column: smiles
  split_column: split
  val_tag: test
  datadir: data/BanyulsInference
  filter: False
  split_file: data/BanyulsInference/split.tsv
  stats_dir: null
  labels_file: data/BanyulsInference/labels.tsv
  spec_folder: data/BanyulsInference/spec_files
  subform_folder: data/BanyulsInference/subformulae/default_subformulae
  max_peaks: null
  morgan_r: 2
  morgan_nbits: 2048
  augment_data: False
  magma_aux_loss: False
  magma_folder: null
  inten_transform: float
  cls_type: ms1
  forward_labels: null
  augment_prob: 1.0
  remove_prob: 0.1
  remove_weights: exp
  inten_prob: 0.1
  forward_aug_folder: null
  magma_modulo: 512
  max_count: null
  fp_file: null
  remove_h: null
  denoise_nodes: False
  merge: downproject_4096
  spec_features: peakformula
  mol_features: fingerprint
  cache_featurizers: True
  set_pooling: cls

model:
  d: 256
  de: 64
  dy: 64
  n_heads: 8
  n_layers: 5
  y_update: True
  no_y: False
  diffusion_steps: 500
  noise_strategy: distribution
  last_layer: mlp
  num_ev: 2
  extra_features:
    - laplacian_embedding
    - node_cycle
    - valence_features

spectra_encoder:
  form_embedder: float
  output_size: 4096
  hidden_size: 256
  spectra_dropout: 0.1
  top_layers: 2
  magma_modulo: 2048
  peak_attn_layers: 4
  set_pooling: intensity
  pairwise_featurization: False
  num_heads: 8
  embed_instrument: False
  inten_transform: float
  no_diffs: False
  refine_layers: 0

train:
  batch_size: 512
  num_train_steps: 40000
  loss_ratio: 1
  starting_learning_rate: 0.0002
  final_learning_rate: 0.000001
  learning_rate_schedule: cosine
  save_path: logs/qm9_experiment
  save_steps: 1000
  num_workers: 4
  seed: 24

valid:
  batch_size: 1024
  num_samples: 1024
  num_eval_steps: 4000
